[package]
name = "only_standalone"
version = "0.1.0"
edition = "2021"
description = "A standalone executable for Stateset API"
publish = false

[[bin]]
name = "only_standalone"
path = "main.rs"

[dependencies]
axum = "0.7.1"
tokio = { version = "1.34.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = "0.3"