use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tracing::{error, info, instrument};
use validator::Validate;

use crate::{
    db::DbPool,
    errors::ServiceError,
    events::{Event, EventSender},
    models::{promotion, PromotionStatus},
};
use sea_orm::{ActiveModelTrait, ActiveValue::Set, DatabaseConnection, EntityTrait};

#[derive(Debug, Serialize, Deserialize, Validate)]
pub struct CreatePromotionCommand {
    #[validate(length(min = 1))]
    pub name: String,

    #[validate(range(min = 0.0))]
    pub discount_percentage: f64,

    #[validate]
    pub start_date: chrono::NaiveDateTime,

    #[validate]
    pub end_date: chrono::NaiveDateTime,

    pub applicable_products: Option<Vec<i32>>, // Product IDs this promotion applies to
}

#[async_trait::async_trait]
impl Command for CreatePromotionCommand {
    type Result = promotion::Model;

    #[instrument(skip(self, db_pool, event_sender))]
    async fn execute(&self, db_pool: Arc<DbPool>, event_sender: Arc<EventSender>) -> Result<Self::Result, ServiceError> {
        self.validate_promotion_dates()?;
        
        let db = db_pool.clone();

        let promotion = self.build_promotion();

        let saved_promotion = self.save_promotion(&db, promotion).await?;

        self.log_and_trigger_event(event_sender, &saved_promotion).await?;

        Ok(saved_promotion)
    }
}

impl CreatePromotionCommand {
    fn validate_promotion_dates(&self) -> Result<(), ServiceError> {
        if self.start_date >= self.end_date {
            error!("Promotion start date must be before end date");
            return Err(ServiceError::ValidationError("Promotion start date must be before end date".to_string()));
        }
        Ok(())
    }

    fn build_promotion(&self) -> promotion::ActiveModel {
        promotion::ActiveModel {
            id: Set(0), // Assuming this will be auto-generated by the database
            name: Set(self.name.clone()),
            discount_percentage: Set(self.discount_percentage),
            start_date: Set(self.start_date),
            end_date: Set(self.end_date),
            status: Set(PromotionStatus::Active),
            created_at: Set(Some(chrono::Utc::now().naive_utc())),
            updated_at: Set(Some(chrono::Utc::now().naive_utc())),
            ..Default::default()
        }
    }

    async fn save_promotion(&self, db: &DatabaseConnection, promotion: promotion::ActiveModel) -> Result<promotion::Model, ServiceError> {
        promotion
            .insert(db)
            .await
            .map_err(|e| {
                error!("Failed to save promotion: {:?}", e);
                ServiceError::DatabaseError
            })
    }

    async fn log_and_trigger_event(&self, event_sender: Arc<EventSender>, promotion: &promotion::Model) -> Result<(), ServiceError> {
        info!("Promotion created: {:?}", promotion);

        event_sender
            .send(Event::PromotionCreated(promotion.id))
            .await
            .map_err(|e| {
                error!("Failed to send PromotionCreated event: {:?}", e);
                ServiceError::EventError(e.to_string())
            })
    }
}
